Args=--initialize-at-build-time=org.slf4j.helpers.NOPLoggerFactory \
     --initialize-at-build-time=org.pg.enums.TxLevel \
     --initialize-at-build-time=org.pg.enums.CopyFormat \
     --initialize-at-build-time=org.pg.enums.TXStatus